services:
  # Web Dashboard
  - type: web
    name: wavesight-dashboard
    env: node
    region: oregon # optional
    buildCommand: cd web && npm install && npm run build
    startCommand: cd web && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://achuavagkhjenaypawij.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjaHVhdmFna2hqZW5heXBhd2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTY0MjQsImV4cCI6MjA2ODE3MjQyNH0.L4J5SIVGZDYAFAwNuR9b_hIvcpTJWGfu0Dvry7Umg2g
      - key: NEXT_PUBLIC_API_URL
        value: https://your-backend-api.onrender.com # Update this after deploying backend

  # Backend API (optional - uncomment if you want to deploy backend too)
  # - type: web
  #   name: wavesight-api
  #   runtime: python
  #   region: oregon
  #   buildCommand: cd backend && pip install -r requirements.txt
  #   startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
  #   envVars:
  #     - key: DATABASE_URL
  #       value: postgresql://postgres:[qIvwos-vujzy1-dopzeb]@db.achuavagkhjenaypawij.supabase.co:5432/postgres
  #     - key: JWT_SECRET
  #       generateValue: true
  #     - key: REDIS_URL
  #       value: # Add Redis URL if needed