# Mobile App Build Service
# This service builds and serves the React Native mobile app bundle
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wavesight-mobile
  namespace: wavesight
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wavesight-mobile
  template:
    metadata:
      labels:
        app: wavesight-mobile
    spec:
      containers:
      - name: mobile
        image: wavesight/mobile:latest
        ports:
        - containerPort: 8081
        env:
        - name: NODE_ENV
          value: "production"
        - name: BACKEND_URL
          value: "https://api.wavesight.yourdomain.com"
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: wavesight-secrets
              key: supabase-url
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: wavesight-secrets
              key: supabase-anon-key
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: wavesight-mobile-service
  namespace: wavesight
spec:
  selector:
    app: wavesight-mobile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
---
# Horizontal Pod Autoscaler for mobile service
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wavesight-mobile-hpa
  namespace: wavesight
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wavesight-mobile
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80